[MIBM-114][JR] /tax-calculation
hmrc/merchandise-in-baggage-frontend pull request #52
Opened 2020-10-13 12:26 UTC by jordanrowe

2020-10-13 12:46 UTC, PasGat approved these changes

2020-10-13 12:59 UTC, PaulHodgson commented on app/uk/gov/hmrc/merchandiseinbaggagefrontend/model/core/Declaration.scala
> -  val totalTaxDue: AmountInPence = AmountInPence(goods.map(g => g.taxDue.value).sum.max(0))
why not remove now?

2020-10-13 12:59 UTC, PaulHodgson requested changes
This story hasn't been through refinement.

2020-10-14 09:23 UTC, PaulHodgson commented on app/uk/gov/hmrc/merchandiseinbaggagefrontend/views/CheckYourAnswersPage.scala.html
> +@(form: Form[_], declaration: Declaration, taxDue: AmountInPence)(implicit request: Request[_], messages: Messages, appConfig: AppConfig)
Cool thanks

2020-10-14 09:24 UTC, PaulHodgson approved these changes

2020-10-14 09:24 UTC, merged